services:
  api:
    image: hackaton-project/api
    container_name: hackaton-api-container
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: hackaton-db-container
    build:
      context: ./bdd
      dockerfile: Dockerfile
    image: hackaton-project/db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tomyj
      MYSQL_PASSWORD: tomyj123
    volumes:
      - mysql_data:/var/lib/mysql
  front:
    image: hackaton-project/front
    container_name: hackaton-front-container
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "30033:80"
    restart: unless-stopped

volumes:
  mysql_data:
